apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythondemoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythondemoapp
  template:
    metadata:
      labels:
        app: pythondemoapp
    spec:
      containers:
      - name: pythondemoapp
        image: asia-south1-docker.pkg.dev/planar-sun-412213/nadeem-cicd-usecase-dev-repo/pythondemoimage:${imageTag}
        ports:
        - containerPort: 9090